import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {promisify} from 'node:util';
import {gzipSync,gunzipSync} from 'node:zlib';
import {validateFamily} from './family.mjs';
import {defaults,validateSettings,readJSON} from './settings.mjs';
const scrypt=promisify(crypto.scrypt),allowed=['settings.json','secrets.json','family.json','tokens.json','google-tokens.json'];
export class Backup {
 constructor(data,state=()=>null){this.data=data;this.state=state;this.queue=Promise.resolve();}
 async files(){const files={};let bytes=0;for(const name of allowed){try{files[name]=(await fs.readFile(path.join(this.data,name))).toString('base64');}catch(e){if(e.code!=='ENOENT')throw e;}}for(const name of await fs.readdir(path.join(this.data,'photos')))if(/^[a-f\d-]+\.jpg$/.test(name)){const file=path.join(this.data,'photos',name);bytes+=(await fs.stat(file)).size;if(bytes>70*1024*1024)throw Error('Uploaded photos exceed the downloadable backup limit. Use a host volume backup.');const b=await fs.readFile(file);files['photos/'+name]=b.toString('base64');}return files;}
 async create(password){if(typeof password!=='string'||password.length<10||password.length>200)throw Error('Backup passphrase needs 10–200 characters');const files=await this.files(),state=this.state();files['settings.json']=Buffer.from(JSON.stringify(state?.settings||await readJSON(this.data,'settings.json',defaults))).toString('base64');files['secrets.json']=Buffer.from(JSON.stringify(state?.secrets||await readJSON(this.data,'secrets.json',{}))).toString('base64');const raw=Buffer.from(JSON.stringify({format:'homeboard-backup',version:1,created:new Date().toISOString(),files}));if(raw.length>100*1024*1024)throw Error('Backup exceeds 100 MB; back up large photo volumes on the host');const salt=crypto.randomBytes(32),iv=crypto.randomBytes(12),key=await scrypt(password,salt,32),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([cipher.update(gzipSync(raw)),cipher.final()]);return {format:'homeboard-encrypted-backup',version:1,salt:salt.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:encrypted.toString('base64')};}
 async decode(value,password){if(!value||value.format!=='homeboard-encrypted-backup'||value.version!==1||typeof value.data!=='string'||value.data.length>140*1024*1024||typeof password!=='string'||password.length<10||password.length>200)throw Error('Invalid encrypted backup or passphrase');let raw;try{const salt=Buffer.from(value.salt,'base64'),iv=Buffer.from(value.iv,'base64'),tag=Buffer.from(value.tag,'base64');if(salt.length!==32||iv.length!==12||tag.length!==16)throw Error();const key=await scrypt(password,salt,32),decipher=crypto.createDecipheriv('aes-256-gcm',key,iv);decipher.setAuthTag(tag);raw=gunzipSync(Buffer.concat([decipher.update(Buffer.from(value.data,'base64')),decipher.final()]),{maxOutputLength:100*1024*1024});}catch{throw Error('Backup cannot be decrypted. Check the passphrase and file.');}const archive=JSON.parse(raw);if(archive.format!=='homeboard-backup'||archive.version!==1||!archive.files||Array.isArray(archive.files))throw Error('Invalid backup');const files={};for(const [name,b64]of Object.entries(archive.files)){if(!allowed.includes(name)&&!/^photos\/[a-f\d-]+\.jpg$/.test(name)||typeof b64!=='string')throw Error('Invalid backup file path');const content=Buffer.from(b64,'base64');if(name.endsWith('.json')){const j=JSON.parse(content);if(name==='settings.json')validateSettings(j,defaults);if(name==='family.json')validateFamily(j);if(name==='secrets.json'&&(!j||typeof j!=='object'||Array.isArray(j)))throw Error('Invalid secrets backup');}else if(content[0]!==0xff||content[1]!==0xd8)throw Error('Invalid backup photo');files[name]=content;}if(!files['settings.json'])throw Error('Backup is missing settings');return files;}
 async restore(value,password){const work=this.queue.then(async()=>{const files=await this.decode(value,password),root=path.join(this.data,'backups'),stamp=new Date().toISOString().replace(/[:.]/g,'-')+'-'+crypto.randomUUID(),rollback=path.join(root,stamp);await fs.mkdir(root,{recursive:true,mode:0o700});await fs.mkdir(rollback,{recursive:true,mode:0o700});const existing=await this.files();for(const [name,b64]of Object.entries(existing)){const target=path.join(rollback,name);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,Buffer.from(b64,'base64'),{mode:0o600});}
  try{for(const [name,content]of Object.entries(files)){const target=path.join(this.data,name),temp=target+'.restore.tmp';await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(temp,content,{mode:0o600});await fs.rename(temp,target);}for(const name of allowed)if(!files[name])await fs.unlink(path.join(this.data,name)).catch(e=>{if(e.code!=='ENOENT')throw e;});for(const name of await fs.readdir(path.join(this.data,'photos')))if(/^[a-f\d-]+\.jpg$/.test(name)&&!files['photos/'+name])await fs.unlink(path.join(this.data,'photos',name));}
  catch(e){for(const name of Object.keys(files))if(!existing[name])await fs.unlink(path.join(this.data,name)).catch(()=>{});for(const [name,b64]of Object.entries(existing)){const target=path.join(this.data,name);await fs.writeFile(target,Buffer.from(b64,'base64'),{mode:0o600});}throw e;}
  return {restored:true,rollback:stamp};});this.queue=work.catch(()=>{});return work;}
 async list(){try{return (await fs.readdir(path.join(this.data,'backups'))).filter(x=>/^\d{4}-/.test(x)).sort().reverse();}catch(e){if(e.code==='ENOENT')return [];throw e;}}
}
