import crypto from 'node:crypto';
const ENDPOINT='https://api.octopus.energy/v1/graphql/';
const AUTH='mutation HomeBoardOctopusToken($input: ObtainJSONWebTokenInput!) { obtainKrakenToken(input: $input) { token payload } }';
const DEVICES='query HomeBoardOctopusDevices($accountNumber: String!) { devices(accountNumber: $accountNumber) { id name deviceType provider } }';
const SLOTS='query HomeBoardOctopusSchedule($deviceId: String!) { flexPlannedDispatches(deviceId: $deviceId) { start end type energyAddedKwh } }';
function failure(code){const e=Error(code==='KT-CT-1199'||code===429?'Octopus request limit reached. Retrying later.':['KT-CT-1113','KT-CT-11334'].includes(code)?'Octopus does not expose smart charging schedules for this account or device.':['KT-CT-1111','KT-CT-1112','KT-CT-1120','KT-CT-1134','KT-CT-1135',401,403].includes(code)?'Octopus rejected access. Check the account ID and API key.':'Octopus is unavailable or returned an invalid schedule.');e.status=['KT-CT-1113','KT-CT-11334'].includes(code)?'unsupported':'unavailable';e.code=code;return e;}
export class Octopus {
 constructor(settings,secrets,{request=globalThis.fetch,now=Date.now}={}){this.settings=settings;this.secrets=secrets;this.request=request;this.now=now;this.cache=new Map();this.pending=new Map();this.tokens=new Map();}
 fingerprint(){const s=this.secrets();return crypto.createHash('sha256').update(JSON.stringify([s.octopusAccountId,s.octopusApiKey,this.settings().octopusDeviceId])).digest('hex');}
 async graphql(query,variables,token){let r,j;try{r=await this.request(ENDPOINT,{method:'POST',redirect:'error',signal:AbortSignal.timeout(15000),headers:{'Content-Type':'application/json',...(token?{Authorization:token}:{})},body:JSON.stringify({query,variables})});if(!r.ok)throw failure(r.status);const text=await r.text();if(text.length>1000000)throw failure();j=JSON.parse(text);}catch(e){throw e.code?e:failure();}if(j.errors?.length)throw failure(j.errors[0].extensions?.errorCode);if(!j.data||typeof j.data!=='object')throw failure();return j.data;}
 async token(key,secrets){let t=this.tokens.get(key);if(t&&t.expires>this.now()+60000)return t.token;const data=await this.graphql(AUTH,{input:{apiKey:secrets.octopusApiKey}}),value=data.obtainKrakenToken;if(typeof value?.token!=='string'||!value.token||/[\r\n]/.test(value.token))throw failure();t={token:value.token,expires:Number(value.payload?.exp)*1000||this.now()+300000};this.tokens.set(key,t);return t.token;}
 async schedule({refresh=false}={}){const s=this.settings(),secrets={...this.secrets()};if(!s.octopusEnabled)return {enabled:false,status:'disabled',slots:[]};if(!secrets.octopusAccountId||!secrets.octopusApiKey)return {enabled:true,status:'unconfigured',slots:[],error:'Add your Octopus account ID and API key in Settings → Smart charging.'};const key=this.fingerprint(),cached=this.cache.get(key),now=this.now();if(cached&&now<cached.next&&(cached.result.error||!refresh||now-cached.checked<60000))return cached.result;if(this.pending.has(key))return this.pending.get(key);const job=this.load(key,s,secrets,cached);this.pending.set(key,job);try{return await job;}finally{this.pending.delete(key);}}
 async load(key,s,secrets,cached){const now=this.now();try{let token=await this.token(key,secrets),data;try{data=await this.graphql(DEVICES,{accountNumber:secrets.octopusAccountId},token);}catch(e){if(e.code!=='KT-CT-1120')throw e;this.tokens.delete(key);token=await this.token(key,secrets);data=await this.graphql(DEVICES,{accountNumber:secrets.octopusAccountId},token);}if(!Array.isArray(data.devices)||data.devices.length>100)throw failure();const devices=data.devices.filter(d=>['ELECTRIC_VEHICLES','CHARGE_POINTS','EV_CHARGERS','ELECTRIC_VEHICLE'].includes(d.deviceType)).map(d=>{if(typeof d.id!=='string'||d.id.length>200||typeof d.name!=='string'||d.name.length>200)throw failure();return {id:d.id,name:d.name,provider:typeof d.provider==='string'?d.provider.slice(0,80):''};});const device=s.octopusDeviceId?devices.find(d=>d.id===s.octopusDeviceId):devices[0];if(!device){const result={enabled:true,status:devices.length?'device-missing':'unsupported',devices,slots:[],error:devices.length?'The selected charging device is no longer available. Select a device in Settings.':'No supported Intelligent Octopus charging device was found.',updated:new Date(now).toISOString()};return this.store(key,result,now);}
 const schedule=await this.graphql(SLOTS,{deviceId:device.id},token);if(!Array.isArray(schedule.flexPlannedDispatches)||schedule.flexPlannedDispatches.length>500)throw failure();const slots=schedule.flexPlannedDispatches.map(x=>{if(typeof x.start!=='string'||typeof x.end!=='string'||!/(Z|[+-]\d{2}:\d{2})$/.test(x.start)||!/(Z|[+-]\d{2}:\d{2})$/.test(x.end))throw failure();const start=Date.parse(x.start),end=Date.parse(x.end),energy=x.energyAddedKwh==null?null:Number(x.energyAddedKwh);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>7*86400000||energy!==null&&(!Number.isFinite(energy)||energy<0))throw failure();return {start:new Date(start).toISOString(),end:new Date(end).toISOString(),source:['SMART','BOOST','TEST'].includes(x.type)?x.type:'OTHER',energyKwh:energy};}).filter(x=>Date.parse(x.end)>now).sort((a,b)=>a.start.localeCompare(b.start));const result={enabled:true,status:slots.length?'scheduled':'waiting',device,devices,slots,updated:new Date(now).toISOString(),stale:false};return this.store(key,result,now);
 }catch(e){const old=cached?.result,usable=old?.updated&&now-Date.parse(old.updated)<1800000;const result=usable?{...old,stale:true,error:failure(e.code).message}:{enabled:true,status:e.status||'unavailable',slots:[],devices:[],error:failure(e.code).message};return this.store(key,result,now);}}
 store(key,result,now){if(key!==this.fingerprint())return {enabled:this.settings().octopusEnabled,status:'unavailable',slots:[],error:'Connection changed. Refresh to load the new schedule.'};this.cache.clear();this.cache.set(key,{result,checked:now,next:now+300000});return result;}
}
